export * from './schema/socios';
export * from './schema/tipos-actividad';
export * from './schema/actividades';
export * from './schema/asistencia';
export * from './schema/aportes';
export * from './schema/multas';
export * from './schema/movimientos';
export * from './schema/egresos';
export * from './schema/config';
